# toml-configuration file for vba_codereader
# for details of toml-syntax see https://toml.io/en/

# output directory for exported office VBA files
# the files will be named like the office file but with '*.txt' extension
# the directory must exist
# use single backslashes for windows pathes
# pathes starting with a dot like '.\VBA2Parse' are relativ to the dir current working dir

# Target directory
outdir = '.\tests\integration\data\VBA2Parse'

# list of office files, whose vba-software should be exported
# 
# [[filelist]] defines an toml-"array of tables"
# You can have multiple [[filelist]]-statements in your vba_codereader.toml
# Each one has to be followed by one >>path = "path\to\my\directory\with\excelfiles"<< statement
# this has to follow the same rules as >>outdir<< above
# After the path-statement there must be one >>files = [list, of, files]<< statement,
# which defines a list of files inside >>path<<
# * as wildcard is allowed

# first list of files to be processed
[[filelist]]
path = 'V:\Tools\Excel Makros'
files = [
    'M*.xl*',
    'Excel_file.xlsm',
]

# second list of files to be processed
[[filelist]]
path = '..'
files = [
    'myworkbook.xlsm',
]